### ISSUE TITLE
make sure readme is up to date

### ISSUE THREAD

**Issue by kejace** [blockapps/pizza-demo#21]

**Comment by kejace** [comment]
Just simplified a bunch. It is now essentially

`npm i; npm start` assuming the config is correctly pointed to the `silo` node.

**Comment by kejace** [comment]
@martyall can you double check that this works for you? you can use the default checked-in config.

**Comment by Adele94** [comment]
hello! i have a problem with npm start. " Tell the author that this fails on your system:
npm ERR!     node ./createusers.js "

**Comment by Adele94** [comment]
hello! Sorry, but i have a problem with npm start. " Error: Cannot find module '/Users/Adele/pizza-demo/createusers.js'
Tell the author that this fails on your system:
npm ERR!     node ./createusers.js
"

**Comment by kejace** [comment]
@Adele94 I had forgotten to add it to the repo, please pull latest and try again.
